language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
deploy:
  provider: releases
  api_key: "9a6b191e1fda1547b06a489f10a7ad4547e90754"
  file:
  - "./Build/windows/Course-Project.exe"
  - "./Build/osx/Course-Project.app"
  - "./Build/linux/Course-Project"
  skip_cleanup: true
  on:
    tags: true
